### ISSUE TITLE
create agent error agents</code> was not found on this server. 

### ISSUE THREAD

**Issue by amithit** [google-business-communications/bc-bm-nodejs-command-line-examples#1]
I am trying to create agent or get the list of agent , i am getting 404 error as requested url not found .

{
  config: {
    url: 'https://businesscommunications.googleapis.com/v1/new-Lifedata-test/agents',
    method: 'POST',
    paramsSerializer: [Function],
    data: { displayName: 'A Test Agent', businessMessagesAgent: [Object] },
    headers: {
      'Accept-Encoding': 'gzip',
      'User-Agent': 'google-api-nodejs-client/0.7.2 (gzip)',
      Authorization: 'Bearer <token>...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',
      'Content-Type': 'application/json',
      Accept: 'application/json'
    },
    params: [Object: null prototype] {},
    validateStatus: [Function],
    body: '{"displayName":"A Test Agent","businessMessagesAgent":{"defaultLocale":"en","customAgentId":"","logoUrl":"https://storage.googleapis.com/sample-logos/google-logo.png","conversationalSettings":{"en":{"privacyPolicy":{"url":"http://www.company.com/privacy"},"welcomeMessage":{"text":"Welcome! How can I help?"},"offlineMessage":{"text":"We are currently offline, please leave a message and we will get back to you as soon as possible."},"conversationStarters":[{"suggestion":{"reply":{"text":"Chip #1","postbackData":"chip_1"}}},{"suggestion":{"reply":{"text":"Chip #2","postbackData":"chip_2"}}},{"suggestion":{"reply":{"text":"Chip #3","postbackData":"chip_3"}}},{"suggestion":{"reply":{"text":"Chip #4","postbackData":"chip_4"}}},{"suggestion":{"action":{"text":"Chip #5","postbackData":"chip_5","openUrlAction":{"url":"https://www.google.com"}}}}]}},"entryPointConfigs":[{"allowedEntryPoint":"LOCATION"},{"allowedEntryPoint":"NON_LOCAL"}],"nonLocalConfig":{"callDeflectionPhoneNumbers":[{"number":"+11557519068"}],"contactOption":{"options":["WEB_CHAT","FAQS"],"url":"https://www.example-url.com"},"enabledDomains":["https://www.a8034o8hbl.com"],"phoneNumber":{"number":"+919113055420"},"regionCodes":["CA","US"]},"primaryAgentInteraction":{"interactionType":"BOT","botRepresentative":{"botMessagingAvailability":{"hours":[{"startTime":{"hours":"0","minutes":"0"},"endTime":{"hours":"23","minutes":"59"},"timeZone":"Africa/Bamako","startDay":"MONDAY","endDay":"SUNDAY"}]}}},"additionalAgentInteractions":{"interactionType":"HUMAN","humanRepresentative":{"humanMessagingAvailability":{"hours":[{"startTime":{"hours":"0","minutes":"0"},"endTime":{"hours":"23","minutes":"59"},"timeZone":"Africa/Bamako","startDay":"MONDAY","endDay":"SUNDAY"}]}}},"surveyConfig":{"templateQuestionIds":["GOOGLE_DEFINED_ASSOCIATE_SATISFACTION"],"customSurveys":{"en":{"customQuestions":[{"name":"custom_question_1","questionType":"PARTNER_CUSTOM_QUESTION","questionContent":"Did this agent do the best that it could?","responseOptions":[{"content":"👍","postbackData":"yes"},{"content":"👎","postbackData":"no"}]}]}}}}}',
    responseType: 'json'
  },
  data: '<!DOCTYPE html>\n' +
    '<html lang=en>\n' +
    '  <meta charset=utf-8>\n' +
    '  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n' +
    '  <title>Error 404 (Not Found)!!1</title>\n' +
    '  <style>\n' +
    '    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n' +
    '  </style>\n' +
    '  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n' +
    '  <p><b>404.</b> <ins>That’s an error.</ins>\n' +
    '  <p>The requested URL <code>/v1/new-Lifedata-test/agents</code> was not found on this server.  <ins>That’s all we know.</ins>\n',
  headers: {
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
    connection: 'close',
    'content-length': '1588',
    'content-type': 'text/html; charset=UTF-8',
    date: 'Mon, 04 Oct 2021 07:41:06 GMT',
    server: 'ESF',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'SAMEORIGIN',
    'x-xss-protection': '0'
  },
  status: 404,
  statusText: 'Not Found'
}
(node:11422) UnhandledPromiseRejectionWarning: Error: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/v1/new-Lifedata-test/agents</code> was not found on this server.  <ins>That’s all we know.</ins>

    at Gaxios.<anonymous> (/home/amit/messageGateway/bitbucket/new/channel-adapter/app/node_modules/gaxios/build/src/gaxios.js:73:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/amit/messageGateway/bitbucket/new/channel-adapter/app/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11422) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11422) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

@thefalc @adamjchan

**Comment by thefalc** [comment]
Your URL structure looks incorrect. Posting to  'https://businesscommunications.googleapis.com/v1/new-Lifedata-test/agents', isn't valid. To create an agent, you must first create a brand and then post the agent object to the brands agent endpoint like this: https://businesscommunications.googleapis.com/v1/brands/BRAND_ID/agents

The BRAND_ID should be a UUID format. To create a brand, look at https://github.com/google-business-communications/bc-bm-nodejs-command-line-examples/blob/f202b4e4cea948987bb843bd234b40cd9198f5c0/brand_sample.js#L64

And to create an agent: https://github.com/google-business-communications/bc-bm-nodejs-command-line-examples/blob/f202b4e4cea948987bb843bd234b40cd9198f5c0/agent_sample.js#L155

**Comment by amithit** [comment]
Thanks
@thefalc its working.
